# 02 Random Forest Classification

## Objective
This notebook trains and evaluates a **Random Forest Classifier** for the student dropout prediction task. It reuses the shared preprocessing and evaluation utilities from the project so that results are consistent with the rest of the assignment.

## 1. Import Libraries and Utilities

We import the required libraries and shared project utilities used to train, evaluate, and save the baseline random forest model.

In [1]:
from pathlib import Path
import sys

import pandas as pd
from sklearn.ensemble import RandomForestClassifier

PROJECT_ROOT = Path.cwd().resolve().parent if Path.cwd().name == "notebooks" else Path.cwd().resolve()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from utils import METRICS_DIR, MODELS_DIR, FIGURES_DIR, train_and_evaluate

## 2. Train Baseline Random Forest

This block defines the baseline random forest configuration and performs a small grid search to find a solid starting set of hyperparameters.

In [2]:
random_forest = RandomForestClassifier(
    random_state=42,
    n_jobs=1,
    class_weight="balanced",
)

param_grid = {
    "n_estimators": [200, 300],
    "max_depth": [None, 10, 20],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2],
}

metrics, summary_df = train_and_evaluate(
    model=random_forest,
    model_name="Random Forest",
    param_grid=param_grid,
)

summary_df

,Algorithm,Training Accuracy,Accuracy (Test),Balanced Accuracy,Weighted F1,Macro F1,CV Accuracy Mean
0,Random Forest,0.960723,0.770621,0.709903,0.768502,0.714709,0.774509

## 3. Results Overview

We summarize the main evaluation metrics, the selected hyperparameters, and the saved artifact locations for the baseline model.

In [3]:
pd.Series({
    "Accuracy": metrics["Accuracy"],
    "Balanced Accuracy": metrics["Balanced Accuracy"],
    "Weighted Precision": metrics["Precision (weighted)"],
    "Weighted Recall": metrics["Recall (weighted)"],
    "Weighted F1": metrics["F1-score (weighted)"],
    "Macro F1": metrics["F1-score (macro)"],
    "Best Parameters": metrics.get("Best Parameters", {}),
    "Best CV Weighted F1": metrics.get("Best CV Weighted F1"),
    "Metrics JSON": str(METRICS_DIR / "random_forest.json"),
    "Model File": str(MODELS_DIR / "random_forest.joblib"),
    "Confusion Matrix Figure": str(FIGURES_DIR / "random_forest_confusion_matrix.png"),
})

Accuracy                                                            0.770621
Balanced Accuracy                                                   0.709903
Weighted Precision                                                  0.769416
Weighted Recall                                                     0.770621
Weighted F1                                                         0.768502
Macro F1                                                            0.714709
Best Parameters            {'max_depth': None, 'min_samples_leaf': 2, 'mi...
Best CV Weighted F1                                                 0.769152
Metrics JSON               E:\projects\student-dropout-prediction\results...
Model File                 E:\projects\student-dropout-prediction\results...
Confusion Matrix Figure    E:\projects\student-dropout-prediction\results...
dtype: object

## 4. Classification Report

This report shows class-level precision, recall, and F1-score so we can inspect how the baseline model performs on `Dropout`, `Enrolled`, and `Graduate` separately.

In [4]:
pd.DataFrame(metrics["Classification Report"]).transpose()

              precision    recall  f1-score     support
Dropout        0.821429  0.728873  0.772388  284.000000
Enrolled       0.519231  0.509434  0.514286  159.000000
Graduate       0.825996  0.891403  0.857454  442.000000
accuracy       0.770621  0.770621  0.770621    0.770621
macro avg      0.722218  0.709903  0.714709  885.000000
weighted avg   0.769416  0.770621  0.768502  885.000000